# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-12 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Locus', models.TextField()),
                ('Transcript', models.TextField()),
                ('Allele', models.TextField()),
                ('DNA', models.TextField()),
                ('AA', models.TextField()),
                ('Genome_Build', models.TextField()),
                ('Chromosome', models.TextField()),
                ('Genome_Build_DNA', models.TextField()),
                ('Report_As_Allele', models.TextField()),
                ('Report_As_DNA', models.TextField()),
                ('Report_As_AA', models.TextField()),
                ('Region', models.TextField()),
                ('Cat_Dis', models.TextField()),
                ('Non_inc_Dis', models.TextField()),
                ('Rpt', models.TextField()),
                ('Fam', models.TextField()),
                ('DNA_Type', models.TextField()),
                ('AA_Type', models.TextField()),
                ('Cyto_Type', models.TextField()),
                ('RS', models.TextField()),
                ('ClinVar', models.TextField()),
                ('Source', models.TextField()),
                ('Alias_es', models.TextField()),
                ('Ref', models.TextField()),
            ],
            options={
                'db_table': 'variant',
            },
        ),
    ]
