# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-22 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_autocomplete_words'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('Abbr', models.TextField()),
                ('Inheritance', models.TextField()),
                ('Codes', models.TextField()),
                ('Description', models.TextField()),
                ('Genes', models.TextField()),
                ('Variants', models.TextField()),
            ],
            options={
                'db_table': 'disease',
            },
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Official_Symbol', models.TextField()),
                ('Report_Symbol', models.TextField()),
                ('Chr', models.TextField()),
                ('Loc', models.TextField()),
                ('Diseases_Drugs', models.TextField()),
                ('Variants', models.TextField()),
                ('Full_Name', models.TextField()),
                ('Type', models.TextField()),
                ('Alias_Symbols', models.TextField()),
            ],
            options={
                'db_table': 'gene',
            },
        ),
    ]
